### PR TITLE
 fix(types): add proper generics to accessors

### PR DESCRIPTION
**Pull request by KaelWD**
see #38, https://github.com/davestewart/vuex-pathify/pull/38#issuecomment-446712410

@gil0mendes @ozum you were close

### CODE REVIEW

**Comment by davestewart** [comment]
Hey @KaelWD,

Thanks for this. That sure is pretty code! I've been doing typescript for while, but not to this level.

Do you have any resources for where to learn about doing code like you've written in your tests?

I didn't even know you could do this:

```ts
Vue.extend({
  computed: get<{
    search: string,
    items: any[]
  }>('products', [
    'search',
    'items',
  ]),
```

**Comment by KaelWD** [comment]
If you mean specifically with vue, I don't think there really are any. Otherwise it's mostly just writing TS every day for the past ~year plus a little help from [here](https://basarat.gitbooks.io/typescript/).

**Comment by KaelWD** [comment]
Is this ready to merge?

**Comment by davestewart** [comment]
orry @KaelWD - been really distracted with other things.

**Comment by davestewart** [comment]
Published :)

**Pull request merged**
